A="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Short_Tube/DST_Dress043_1/DST_Dress043_1_obj.usd"
B="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Trousers/Short/PS_043/PS_043_obj.usd"
C="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Long_LongSleeve/DLLS_Dress008_0/DLLS_Dress008_0_obj.usd"
SCARF="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Scarf_Tie/ST_Scarf-001/ST_Scarf-001_obj.usd"
DRESS="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Long_Gallus/DLG_Dress032_1/DLG_Dress032_1_obj.usd"
TOP="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Tops/Collar_Lsleeve_FrontClose/TCLC_002/TCLC_002_obj.usd"
TOP2="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Tops/Collar_Lsleeve_FrontClose/TCLC_015/TCLC_015_obj.usd"
TROUSER="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Trousers/Long/PL_longpants020/PL_longpants020_obj.usd"
DRESS_SHORT="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Long_ShortSleeve/DLSS_Dress037_0/DLSS_Dress037_0_obj.usd"
BED="omniverse://localhost/Users/rigid4cloth/Daybed.usd"
CLOTH_TO_HANG="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Long_ShortSleeve/DLSS_Dress182/DLSS_Dress182_obj.usd"
BED_ROOM="/home/sim/Downloads/bedroom3/bedroom_3/bedroom3.usd"
LIVING_ROOM="/home/sim/Downloads/livingroom_6/livingroom_6/room6.usd"

