A="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Short_Tube/DST_Dress043_1/DST_Dress043_1_obj.usd"
B="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Trousers/Short/PS_043/PS_043_obj.usd"
C="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Long_LongSleeve/DLLS_Dress008_0/DLLS_Dress008_0_obj.usd"
SCARF="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Scarf_Tie/ST_Scarf-001/ST_Scarf-001_obj.usd"
DRESS="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Long_Gallus/DLG_Dress032_1/DLG_Dress032_1_obj.usd"
TOP="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Tops/Collar_Lsleeve_FrontClose/TCLC_002/TCLC_002_obj.usd"
TOP2="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Tops/Collar_Lsleeve_FrontClose/TCLC_015/TCLC_015_obj.usd"
TROUSER="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Trousers/Long/PL_longpants020/PL_longpants020_obj.usd"
DRESS_SHORT="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Long_ShortSleeve/DLSS_Dress037_0/DLSS_Dress037_0_obj.usd"
BED="omniverse://localhost/Users/rigid4cloth/Daybed.usd"
CLOTH_TO_HANG="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Long_ShortSleeve/DLSS_Dress182/DLSS_Dress182_obj.usd"
BED_ROOM="/home/sim/Downloads/bedroom3/bedroom_3/bedroom3.usd"
LIVING_ROOM="/home/sim/Downloads/livingroom_6/livingroom_6/room6.usd"
LIVING_ROOM2="/home/sim/Downloads/livingroom_7/room7.usd"
HUMAN_PATH="omniverse://localhost/Users/test/human_model_usd.usd"
HUMAN_CLOTH="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Tops/Collar_noSleeve_FrontOpen/TCNO_020/TCNO_020_obj.usd"
HUMAN_HAT="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Hat/HA_Hat007/HA_Hat007_obj.usd"
HUMAN_SCARF="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Scarf_Tie/ST_Scarf-005/ST_Scarf-005_obj.usd"
BED_ROOM2="/home/sim/Downloads/bedroom4/bedroom_3/bedroom3.usd"
Fling_dress="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Long_ShortSleeve/DLSS_Dress074/DLSS_Dress074_obj.usd"
pile1="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Tops/Collar_Lsleeve_FrontClose/TCLC_082/TCLC_082_obj.usd"
pile2="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Tops/Collar_Lsleeve_FrontClose/TCLC_Top612/TCLC_Top612_obj.usd"
pile3="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Tops/Collar_Lsleeve_FrontClose/TCLC_top117/TCLC_top117_obj.usd"
pile4="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Trousers/Short/PS_Short141/PS_Short141_obj.usd"
HUMAN_HAT="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Hat/HA_Hat007/HA_Hat007_obj.usd"
WIND_DRESS="/home/sim/isaacgarment/ClothesNetData/ClothesNetM_usd/Dress/Long_Gallus/DLG_Dress032_1/DLG_Dress032_1_obj.usd"


DESK="omniverse://localhost/NVIDIA/Assets/ArchVis/Residential/Furniture/Desks/Desk_01.usd"

BOOK_GRASP="omniverse://localhost/NVIDIA/Assets/ArchVis/Residential/Decor/Books/Book_01.usd"
BOOK_STOP="omniverse://localhost/NVIDIA/Assets/ArchVis/Residential/Decor/Books/PhotoAlbum_Closed.usd"

BOOK0="omniverse://localhost/NVIDIA/Assets/ArchVis/Residential/Decor/Books/Book_02.usd"
BOOK1="omniverse://localhost/NVIDIA/Assets/ArchVis/Residential/Decor/Books/Book_11.usd"
BOOK2="omniverse://localhost/NVIDIA/Assets/ArchVis/Residential/Decor/Books/Book_Spelling.usd"
BOOK3="omniverse://localhost/NVIDIA/Assets/ArchVis/Residential/Decor/Books/OmniConnect2016.usd"
BOOK4="omniverse://localhost/NVIDIA/Assets/ArchVis/Residential/Decor/Books/PhotoAlbum_Closed.usd"